version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mern-network
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: server
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mern_db
    networks:
      - mern-network
    ports:
      - "9000:9000"

  client:
    build: ./client
    container_name: client
    depends_on:
      - server
    networks:
      - mern-network
    ports:
      - "3000:3000"

networks:
  mern-network:
    driver: bridge
